# Alembic Configuration File
# the Alembic environment is found in env.py

# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be named with an ordering prefix like '001_'.
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file and Alembic history.
# If specified as a string it should be in the form of what Python's datetime.timezone
# accepts as a positive or negative offset to UTC, or 'local' to get local timezone.
# string value is passed directly to the `timezone` keyword to datetime.datetime.replace()
# timezone =

# max length of characters to apply to the
# "slug" field of the migration name.
# set to 0 to disable, omitting or negative value defaults to
# 40 such as if the configuration file had `truncated_slug_length = 40`
# truncated_slug_length = 40

# set to 'true' to run the environment under the 'always upgrade' mode, such that the alembic_version
# table is not actually used to track if the migration ran
# this is useful as a ramp tool to keep adding and applying new migrations regardless of their revision number
# (useful when porting a repository that has inconsistent migration ordering)
# sqlalchemy.url is required when this feature is enabled
# always_upgrade = false

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
